name: Android CI

on:
  pull_request:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode and restore keystore
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks
    - name: Check if keystore exists
      run: ls -la app/
        
    - name: Build Signed AAB
      run: ./gradlew bundleRelease \
        -Pandroid.injected.signing.store.file=app/keystore.jks \
        -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
        -Pandroid.injected.signing.key.alias=key0 \
        -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}
    
    - name: Check if keystore exists
      run: ls -la app/release

    # - name: Upload Android Release to Play Store
    #   uses: r0adkll/upload-google-play@v1.1.3
    #     serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
    #     packageName: inu.appcenter.intip_android
    #     releaseFiles: app/build/outputs/bundle/release/app-release.aab
    #     track: production
    #     status: inProgress
    #     inAppUpdatePriority: 2
    #     userFraction: 0.33
    #     whatsNewDirectory: distribution/whatsnew
    #     mappingFile: app/build/outputs/mapping/release/mapping.txt
    #     debugSymbols: app/intermediates/merged_native_libs/release/out/lib
